#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERL_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKSPACE_ROOT="$(cd "${VERL_ROOT}/.." && pwd)"
cd "${VERL_ROOT}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-true}"

PROJECT_NAME="${PROJECT_NAME:-L2S-Stage1-Reproduction}"
RUN_NAME="${RUN_NAME:-deepseek-r1-distill-llama-8b-l2s-stage1}"

MODEL_PATH="${MODEL_PATH:-/root/models/deepseek-ai/DeepSeek-R1-Distill-Llama-8B}"
WORKING_DIR="${WORKING_DIR:-${WORKSPACE_ROOT}}"
TRAIN_FILE="${TRAIN_FILE:-${WORKING_DIR}/datasets/test_data/DeepScaler/train.parquet}"
TEST_FILE="${TEST_FILE:-${WORKING_DIR}/datasets/test_data/AIME24/test.parquet}"
CKPT_PATH="${CKPT_PATH:-${WORKING_DIR}/ckpts/${PROJECT_NAME}/${RUN_NAME}}"

NNODES="${NNODES:-1}"
N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-8}"
N_RESPONSES="${N_RESPONSES:-8}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-64}"
MINIBATCH_SIZE="${MINIBATCH_SIZE:-16}"
MICRO_BATCH_SIZE_PER_GPU="${MICRO_BATCH_SIZE_PER_GPU:-2}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-800}"

MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
MAX_VAL_RESP_LENGTH="${MAX_VAL_RESP_LENGTH:-24000}"
MAX_TOKEN_LENGTH=$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))
MAX_VAL_TOKEN_LENGTH=$((MAX_PROMPT_LENGTH + MAX_VAL_RESP_LENGTH))

TEMPERATURE="${TEMPERATURE:-1.0}"
TOP_P="${TOP_P:-1.0}"
TOP_K="${TOP_K:--1}"
VAL_TEMPERATURE="${VAL_TEMPERATURE:-1.0}"
VAL_TOP_P="${VAL_TOP_P:-0.7}"

LEARNING_RATE="${LEARNING_RATE:-1e-6}"
SP_SIZE="${SP_SIZE:-4}"
GEN_TP="${GEN_TP:-4}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.65}"
PARAM_OFFLOAD="${PARAM_OFFLOAD:-true}"
OPTIMIZER_OFFLOAD="${OPTIMIZER_OFFLOAD:-true}"
MODEL_DTYPE="${MODEL_DTYPE:-bf16}"

EVAL_FREQ="${EVAL_FREQ:-20}"
SAVE_FREQ="${SAVE_FREQ:-400}"

command=(
    python3 -m recipe.repro.main_ppo
    "algorithm.adv_estimator=l2s_stage1_reward_as_advantage"
    "algorithm.use_kl_in_reward=False"
    "custom_reward_function.path=${SCRIPT_DIR}/register_l2s_stage1.py"
    "custom_reward_function.name=compute_score"
    "data.train_files=${TRAIN_FILE}"
    "data.val_files=${TEST_FILE}"
    "data.prompt_key=prompt"
    "data.truncation=left"
    "data.max_prompt_length=${MAX_PROMPT_LENGTH}"
    "data.max_response_length=${MAX_RESPONSE_LENGTH}"
    "data.train_batch_size=${TRAIN_BATCH_SIZE}"
    "data.filter_overlong_prompts=True"
    "actor_rollout_ref.model.path=${MODEL_PATH}"
    "actor_rollout_ref.model.use_remove_padding=True"
    "actor_rollout_ref.model.enable_gradient_checkpointing=True"
    "actor_rollout_ref.actor.use_dynamic_bsz=True"
    "actor_rollout_ref.actor.optim.lr=${LEARNING_RATE}"
    "actor_rollout_ref.actor.optim.lr_warmup_steps=10"
    "actor_rollout_ref.actor.optim.weight_decay=0.1"
    "actor_rollout_ref.actor.ppo_mini_batch_size=${MINIBATCH_SIZE}"
    "actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${MICRO_BATCH_SIZE_PER_GPU}"
    "actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${MAX_TOKEN_LENGTH}"
    "actor_rollout_ref.actor.use_kl_loss=False"
    "actor_rollout_ref.actor.clip_ratio_low=0.2"
    "actor_rollout_ref.actor.clip_ratio_high=0.28"
    "actor_rollout_ref.actor.clip_ratio_c=10.0"
    "actor_rollout_ref.actor.entropy_coeff=0"
    "actor_rollout_ref.actor.grad_clip=1.0"
    "actor_rollout_ref.actor.loss_agg_mode=token-mean"
    "actor_rollout_ref.actor.ulysses_sequence_parallel_size=${SP_SIZE}"
    "actor_rollout_ref.actor.fsdp_config.param_offload=${PARAM_OFFLOAD}"
    "actor_rollout_ref.actor.fsdp_config.optimizer_offload=${OPTIMIZER_OFFLOAD}"
    "actor_rollout_ref.actor.fsdp_config.model_dtype=${MODEL_DTYPE}"
    "actor_rollout_ref.actor.fsdp_config.fsdp_size=-1"
    "actor_rollout_ref.rollout.name=vllm"
    "actor_rollout_ref.rollout.n=${N_RESPONSES}"
    "actor_rollout_ref.rollout.tensor_model_parallel_size=${GEN_TP}"
    "actor_rollout_ref.rollout.dtype=bfloat16"
    "actor_rollout_ref.rollout.gpu_memory_utilization=${GPU_MEMORY_UTILIZATION}"
    "actor_rollout_ref.rollout.enable_chunked_prefill=True"
    "actor_rollout_ref.rollout.max_num_batched_tokens=${MAX_VAL_TOKEN_LENGTH}"
    "actor_rollout_ref.rollout.max_model_len=${MAX_VAL_TOKEN_LENGTH}"
    "actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True"
    "actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${MAX_TOKEN_LENGTH}"
    "actor_rollout_ref.rollout.temperature=${TEMPERATURE}"
    "actor_rollout_ref.rollout.top_p=${TOP_P}"
    "actor_rollout_ref.rollout.top_k=${TOP_K}"
    "actor_rollout_ref.rollout.val_kwargs.temperature=${VAL_TEMPERATURE}"
    "actor_rollout_ref.rollout.val_kwargs.top_p=${VAL_TOP_P}"
    "actor_rollout_ref.rollout.val_kwargs.top_k=${TOP_K}"
    "actor_rollout_ref.rollout.val_kwargs.do_sample=True"
    "actor_rollout_ref.rollout.val_kwargs.n=1"
    "+actor_rollout_ref.rollout.val_kwargs.max_tokens=${MAX_VAL_RESP_LENGTH}"
    "reward_model.enable=False"
    "reward_model.reward_manager=l2s_stage1"
    "+reward_model.reward_kwargs.beta=2.0"
    "+reward_model.reward_kwargs.decay_target=0.01"
    "+reward_model.reward_kwargs.decay_horizon=8192"
    "trainer.logger=['console','swanlab']"
    "trainer.project_name=${PROJECT_NAME}"
    "trainer.experiment_name=${RUN_NAME}"
    "trainer.n_gpus_per_node=${N_GPUS_PER_NODE}"
    "trainer.nnodes=${NNODES}"
    "trainer.val_before_train=True"
    "trainer.test_freq=${EVAL_FREQ}"
    "trainer.save_freq=${SAVE_FREQ}"
    "trainer.total_epochs=10"
    "trainer.total_training_steps=${TOTAL_TRAINING_STEPS}"
    "trainer.default_local_dir=${CKPT_PATH}"
    "trainer.resume_mode=auto"
    "trainer.log_val_generations=10"
)

if [[ "${DRY_RUN:-0}" == "1" ]]; then
    printf '%q ' "${command[@]}"
    printf '\n'
    exit 0
fi

mkdir -p "${CKPT_PATH}"
exec "${command[@]}"
